### ISSUE TITLE
DexieCloud - can not delete shared list

### ISSUE THREAD

**Issue by b-straub** [dexie/Dexie.js#1753] opened 2023-06-20 17:42 UTC
1)

ToDo sample (0d1404bc417191cefdab7712b9b65b3c5f3c4afa)
empty database
login Alice on Browser 1
login Bob on Browser 2
create AliceList on Alice
invite Bob
accept invitation on Bobs side
change Bobs role to Manager on Alice side
delete AliceList on Bobs side
-> list can not be deleted

2) 

ToDo sample (0d1404bc417191cefdab7712b9b65b3c5f3c4afa)
empty database
login Alice on Browser 1
login Bob on Browser 2
create AliceList on Alice
invite Bob
accept invitation on Bobs side
change Bobs role to Owner on Alice side
delete AliceList on Bobs side
-> list can not be deleted

3) 

follow steps from 1) or 2)
delete Bob share on Alice side
delete list on Alice side
-> list can be deleted

4) 

follow steps from 1) or 2)
leave AliceList on Bobs side
delete list on Alice side
-> list can be deleted

After trying some of the steps above there will be always dangling entries in Realm and Member tables even when finally all lists have been deleted. Sometimes a Member dropdown (owner) will be shown for a not shared list after some of the operations.

**Comment by dfahlander** [comment] 2023-06-21 22:28
Confirmed as bug. The server rejects the deletion despite the Bob having manager role or is owner of the realm. Seems that Bob is still not allowed to delete realm members when the individual members are owned by Alice - and therefore the entire transaction fails and rolls back. (The response of the sync operation has one item in the "rejections" array: PermissionsDeniedError: User bob@demo.local (bob@demo.local) is not authorized to delete members in realm rlm~tdl0OZV|O34xU7fMNY53g_ESNUUcal).

On Alice side in step 2, after having transferred ownership to Bob, she isn't either authorized to delete the list as the server claims that she lacks permissions to remove the realm (that now Bob owns). 

I'll investigate.

**Comment by b-straub** [comment] 2023-06-24 07:26
An example for a strange behavior likely related:

ToDo sample (https://github.com/dexie/Dexie.js/commit/0d1404bc417191cefdab7712b9b65b3c5f3c4afa)
empty database
login Alice on Browser 1
login Bob on Browser 2
create AliceList on Alice
invite Bob
accept invitation on Bobs side
leave AliceList on Bobs side

bob member still present in members table
delete AliceList
two members still present in members table

**Comment by dfahlander** [comment] 2023-06-26 12:20
Investigation so far: Bob (being manager) succeeds to delete todo-items, the todo-list and all the members, but fails on the last step to delete the realm now that he's been sawing off his own branch (his member that gave him the manager role) - and the transaction fails and all is restored. Continuing troubleshooting...

**Comment by b-straub** [comment] 2023-06-29 08:15
I updated to ea49a72192137127ef97ef2c93316a9b42cab2f6 and created a fresh DB. I don't see anything fixed. Do I miss something?

When testing case 1 I get:

rejections: (1) [{…}]
0: {name: 'ConstraintError', message: 'Cannot delete a non-empty realm rlm~tdl0O_6DbWryy64qwfi_fowRduDcal', txid: '3oauArire1ZxzeYRxpsIXw=='}

**Comment by dfahlander** [comment] 2023-06-29 09:58
The corresponding server side fix is still in staging. I will upgrade your db later today when I'm by the computer and ping you so you can verify

**Comment by dfahlander** [comment] 2023-06-29 11:20
@b-straub I just lifted two of your DB's to staging: z3ozt49hx and zjkqksqdy. We are 3 customers on staging now with the latest fixes. I'll let it be so for a few days before upgrading production.

**Comment by dfahlander** [comment] 2023-06-29 23:36
Your right we have a bug still - this time from a different reason. The deletion of the realm is due to happening the exact same millisecond (50% of the times) registered before the deletion of the todoList. We're missing a sequencial counter on the transactions client side since timestamp isn't enough reliable.

**Closed** 2023-07-01 00:18 UTC
Labels: bug
