### ISSUE TITLE
InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing with ios safari

### ISSUE THREAD

**Issue by Q8root** [dexie/Dexie.js#1139] opened 2020-10-06 12:32 UTC
I am getting error on log when this get executed:-
```
import React, { useEffect } from "react";
import db from "../config/db";

useEffect(() => {
    db.reads
      .get(props.match.params.id)
      .then((data) => {})
      .catch((e) => {
        console.log(e);
      });
  }, []);
```
```
import Dexie from "dexie";
const db = new Dexie("bookDB");
db.version(2).stores({
  reads: "hash,token,sa,ss",
  books: "hash,token",
});

export default db;
```
I am getting many errors :-

> InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

UserAgent:-

> Mozilla/5.0 (iPhone; CPU iPhone OS 13_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Mobile/15E148 Safari/604.1

I could not find steps that produce the following error, some iPhone's i've tested does not return any error.

**Comment by dfahlander** [comment] 2020-10-06 12:59
This happens when database is closing down when the component is mounted. The reason could be if the application at another place calls db.close(), or if the database is forcibly deleted in devtools, or if there is a newer version of the db loaded in another tab or window, so the db has to close down to resume an upgrade.

It could also be a iOS Safari related issue. Do you only see the issue on Safari or have you just tested it there?

**Comment by Q8root** [comment] 2020-10-06 13:05
> This happens when database is closing down when the component is mounting. The reason could be if the application at another place calls db.close(), or if the database is forcibly deleted in devtools, or if there is a newer version of the db loaded in another tab or window, so the db has to close down to resume an upgrade.
> 
> It could also be a iOS Safari related issue. Do you only see the issue on Safari or have you just tested it there?

All the other components files using the same, import db then use .get or .put method, this issue, regarding the version upgade, currently we have version 2 since 4 months ago, and users who got this error are first time they visit our website.
This error only occurred with ios users.

**Comment by Q8root** [comment] 2020-10-07 08:48
![20201007_114743](https://user-images.githubusercontent.com/33479962/95308731-f1359480-0892-11eb-915d-a168ab57de2d.jpg)
S
![Uploading 20201007_114721.jpg…]
Screenshot showing the user-agent that got the error

**Comment by trackedsupport** [comment] 2021-05-14 20:10
> This happens when database is closing down when the component is mounting. The reason could be if the application at another place calls db.close(), or if the database is forcibly deleted in devtools, or if there is a newer version of the db loaded in another tab or window, so the db has to close down to resume an upgrade.
> 
> It could also be a iOS Safari related issue. Do you only see the issue on Safari or have you just tested it there?

So how should we catch and fix this issue?

**Comment by dfahlander** [comment] 2021-05-14 21:26
> So how should we catch and fix this issue?

Too little info about the cause of this issue to tell. Try make a repro.

* Is the reason that your own application is closing down the db? Fix it in your app.
* Is the reason that another tab/window is loading a newer version of the app, making the old close down? Listen to [db.on('versionchange')](https://dexie.org/docs/Dexie/Dexie.on.versionchange).
* Is the reason due to a bug in Safari? - File an issue in webkit bugzilla.

**Comment by trackedsupport** [comment] 2021-05-14 23:32
I never close the dexie db. 
I can't reproduce but I know it happened for someone using Firefox 88 on windows. Also I know that once I changed from storing blobs to storing ArrayBuffer that this issue happens a lot more frequently. 
I have never changed versions of my db - so that should never be called right?

**Comment by dfahlander** [comment] 2021-05-14 23:44
right. Pay attention to errors occurring before this error happens. Are you also getting quotaexceeded errors? I don't see the reason why the browser closes the db for anything else than an unexpected internal error, but i could be wrong. Would be interesting to know.

**Comment by trackedsupport** [comment] 2021-05-15 00:18
I wasn’t getting quotaexceeded until I did the ArrayBuffer but still I’m get those error far less frequently. 

The one Firefox user didn’t have any issues when saving blob without doing the ArrayBuffer. I wouldn’t know there was an issue until I saw only 15 bytes retrieved from the db.

**Comment by Q8root** [comment] 2021-05-15 00:55
> > So how should we catch and fix this issue?
> 
> Too little info about the cause of this issue to tell. Try make a repro.
> 
> * Is the reason that your own application is closing down the db? Fix it in your app.
> * Is the reason that another tab/window is loading a newer version of the app, making the old close down? Listen to [db.on('versionchange')](https://dexie.org/docs/Dexie/Dexie.on.versionchange) to customize how your app should act when this happens.
> * Is the reason due to a bug in Safari? - File an issue in webkit bugzilla.

I begin to think that it's a bug in Safari, because i noticed not only indexedDB data get cleared from those users, also the localStorage get cleared.

**Comment by quolpr** [comment] 2021-05-17 13:35
Yep, it is a safari bug - https://bugs.webkit.org/show_bug.cgi?id=197050 . It may happen when you switch the site between foreground and background.

**Comment by dfahlander** [comment] 2021-05-17 13:51
Thanks @quolpr! Yes, that would be great if we could workaround this. I posted an [idea](https://github.com/dfahlander/Dexie.js/issues/613#issuecomment-841628470) on how to fix it Based on [mikekreeki's workaround](https://github.com/dfahlander/Dexie.js/issues/613#issuecomment-841608979) but without having to test IDB state for every request.

**Comment by jcimoch** [comment] 2021-06-18 07:03
This is ocurring on latest chrome randomly as well, I noticed that it happens more often when browser was put in the background for a while

**Comment by jeremad** [comment] 2022-02-16 13:42
https://github.com/dexie/Dexie.js/pull/1398

Might fix that?

**Comment by dfahlander** [comment] 2022-02-16 15:30
> #1398
> 
> Might fix that?

Yes, #1398 works around the exact same problem - catches exception thrown when executing db.transaction and reopens the connection. It's released in version 3.2.1.

**Closed by dfahlander** 2022-02-16 15:30 UTC

**Comment by jeremad** [comment] 2022-02-17 07:43
Thank you, I'll test test that!

**Comment by jeremad** [comment] 2022-02-17 08:21
It seems indeed to workaround the issue pretty well! Thank you!
