### ISSUE TITLE
Opening IndexdDB exception

### ISSUE THREAD

**Issue by mgovahi** [dexie/Dexie.js#543] opened 2017-05-31 08:37 UTC
Hi,
What is reason of  opening DB  exception "UnknownError: Internal error opening backing store for indexedDB"?
As I checked, When a transaction is running, any try to open DB raise this exception.
I run transaction with mode r!,rw!.
also when my transaction is ongoing , isOpen method return false value .

**Comment by dfahlander** [comment] 2017-05-31 21:08
That exception happens when your browser's database is corrupt. Can happen for various reasons depending on browser. I've seen this error very rarely. What OS / browser are you on?

**Comment by mgovahi** [comment] 2017-07-24 06:32
Hi,
My OS is Windows 10 and browser Google Chrome.

**Comment by dfahlander** [comment] 2017-07-24 08:24
Google Chrome has a stable implementation except that it fails silently on quota exceeded. Make sure your DB has not reached the quota limit for your site. Other than that, I could only think of a corrupt hard disk or broken Google Chrome installation.

**Comment by bennyn** [comment] 2017-10-26 09:32
Hi @dfahlander, I need to bring this topic up again because the `UnknownError` with message "`Internal error opening backing store for indexedDB.open.`" occurred again.

The MacBook of a colleague restarted unexpectedly while he used a web application with Dexie (IndexedDB). After the restart he reopened the web application and got the error. So it looks like the unexpected MacBook restarted ruined the database (which can now no longer be used).

Does IndexedDB support database journaling at all or is there any other activity that can be done to prevent such data loss? Can the IndexedDB get repaired?

**Comment by dfahlander** [comment] 2017-10-26 15:51
There is nothing about disaster recovery in the indexedDB standard what I know of.

**Comment by ankit-prajapati-26** [comment] 2022-10-31 13:00
@dfahlander I am also facing this error when performing the delete operation. is the above issue resolved in newer versions or still exist ? we are using version `3.2.2`

```
db.devicelogs
    .where(schema.deviceLogs)
    .between(startRange, endRange, true, true)
    .delete()
    .catch((e) => {
      if (e && e.name !== 'OpenFailedError') {
        console.log("Error: ", e)
      }
    });
 ```

**Comment by Walexander** [comment] 2023-11-06 17:58
I am able to replicate this error consistently in 118.0.5993.70 using a **very** specific set of steps:
1. [On this page,](https://cdpn.io/walexander/fullpage/oNmBWPy?nocache=true&view=) Click + to add a couple items to the database.
2. Clear all Cookie & Site Data. (Click the Lock icon to the left of the URL bar and go to Cookies & Site Data -> Manage.  Then click the Trash button.)
3. **Without reloading the page** click the + button again. The count should go to 1 and, except for a warning in the console, all will appear normal.  Clicking + multiple times will continue to increment the count.
4. At this point, reloading the page will  lead to an `UnknownError Internal error opening backing store for indexedDB.open.`
5. Reloading the page again will work -- although edits made after the previous deletion are lost.

The problem does ***not*** occur when: 
1. The page is reloaded after clearing Site data *without* pressing the button (creating another Dexie transaction).
2. Manually deleting the database via Dev Tools - *only* occurs when using the Clear Cookie & Site Data.

The code pen editor page is here: https://codepen.io/walexander/pen/oNmBWPy

**Comment by dfahlander** [comment] 2023-11-06 18:06
It sounds marvelous that you found a way to reproduce this. Hopefully this repro could help chromium devs to fix the issue, but I'll start by verifying this and that it's not a Dexie issue before filling it further to the chromium bug tracker.

**Comment by dfahlander** [comment] 2023-11-08 09:31
I tested the [repro](#issuecomment-1795736695) and it fails with UnknownError every time I repeat that procedure. I also use Chrome 118.0.5993.70 (on Arm64 (mac)).

I can confirm this is not a bug in dexie but a Chromium bug that need to be reported in Chromium bug tracker.

The good news is that the issue could be worked around by catching "UnknownError" and retry opening the database. I implemented the workaround in dexie and repeated the repro 10-15 times and the repro never failed to reopen the database the 2nd time so the workaround seems to solve this - at least when reproduced as described in the repro.

Immediately after clearing the site data, another chrome-issue is also being hit (#613) - that the call to db.transaction() fails with "InvalidState". This issue has already [a workaround](#1398) - so that dexie is able to reopen the database and retry the call to db.transaction(). Thanks to that workaround, the database succeeds to reopen the database when clicking the plus icon after clearing site data. After refreshing page we get the "UnknownError" instead, but by catching "UnknownError" from db.open() and doing a similar workaround there (retry db.open()) it seems to be successful to workaround both issues.

A new version of dexie@3 and dexie@4 will be out soon with the workaround.

It would be great if someone could report this issue to [chromium bug tracker](
https://bugs.chromium.org/p/chromium/issues/list?q=component%3ABlink%3EStorage%3EIndexedDB&can=2). Please post here a link to reported bug and refer to the repro we have in this bug. There's already [a similar issue since 2020](https://bugs.chromium.org/p/chromium/issues/detail?id=1085724&q=component%3ABlink%3EStorage%3EIndexedDB%20UnknownError&can=2) in chromium bug tracker.

**Comment by dfahlander** [comment] 2023-11-29 13:43
A workaround for this issue was released in dexie@4.0.1-beta.2. The workaround is not release for dexie@3.x (stable) yet.

**Closed by dfahlander** 2023-11-29 13:43 UTC

**Comment by bennycode** [comment] 2023-11-29 13:52
It's amazing to see that Dexie continues to receive updates even after so many years. Keep up the good work, @dfahlander! 💪 

Dexie is still an [integral part](https://github.com/wireapp/wire-webapp/blob/2023-10-19-production.0/package.json#L107) of [Wire's messenger](https://en.wikipedia.org/wiki/Wire_(software)). ⭐

**Comment by timohausmann** [comment] 2024-06-27 10:40
I, too, get this error in Google Chrome with Dexie 3.2.4 when I use the browser function to delete all website data and reload the page.

**Comment by timohausmann** [comment] 2024-06-27 10:51
I get this error too with Dexie 3.2.4, macOS, Chrome 124.0.6367.93 (arm64). I encounter it after using the browser function to delete all website data. Will the workaround still be released to Dexie 3?

**Comment by dfahlander** [comment] 2024-06-27 11:56
> I get this error too with Dexie 3.2.4, macOS, Chrome 124.0.6367.93 (arm64). I encounter it after using the browser function to delete all website data and reloading the page. Will the workaround still be released to Dexie 3?

It was released in 3.2.5. Latest 3.x is now 3.2.7.

**Comment by timohausmann** [comment] 2024-06-27 18:05
Oh that's great, thank you, I will update!

**Comment by evanstade** [comment] 2026-02-27 20:01
Edge developer here. We have been hunting a particular flavor of `UnknownError` on and off for a while. Many thanks to @Walexander for the repro which triggers it. Wish we had stumbled across this issue earlier! Feel free to report future bugs at [crbug.com](https://issues.chromium.org/issues/new?component=1456771&template=0). The fix should ship in Chromium 147. This is not the only source of `UnknownError`, but it's a large percent of them.

As far as #613, that is intended behavior. Open connections are forcibly closed when the user clobbers their data. Not sure there is a viable alternative.
